import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('dataCompensador.csv', sep = ',')
plt.figure(figsize = (2560/96, 1080/96))
plt.plot(data['tempo'], data['referencia'], linewidth = 3, color = 'tab:orange', label = 'Referencia')
plt.plot(data['tempo'], data['rootlocus'], linewidth = 3, color = 'tab:blue', label = 'Root Locus')
plt.plot(data['tempo'], data['bode'], linewidth = 3, color = 'tab:green', label = 'Frequência')
plt.grid()
plt.xlim([0, 25000])
plt.yticks(fontsize = 22)
plt.xticks(fontsize = 22)
plt.xlabel ('Tempo (s)', fontsize = 22)
plt.ylabel('Temperatura (°C)', fontsize = 22)
plt.title('Resposta a rampa', fontsize = 24)
plt.legend(loc = 'upper left', fontsize = 22)
plt.savefig("RespostaComCompensadorAtrasoDeFaseARampa.png",bbox_inches='tight')
plt.show()

data2 = pd.read_csv('dataPIeCompensador.csv', sep = ',')
plt.figure(figsize = (2560/96, 1080/96))
plt.plot(data2['tempo'], data2['referencia'], linewidth = 3, color = 'tab:orange', label = 'Referencia')
plt.plot(data2['tempo'], data2['compensador'], linewidth = 3, color = 'tab:blue', label = 'Compensador')
plt.plot(data2['tempo'], data2['pi'], linewidth = 3, color = 'tab:green', label = 'PI')
plt.grid()
plt.xlim([0, 30000])
plt.yticks(fontsize = 22)
plt.xticks(fontsize = 22)
plt.xlabel ('Tempo (s)', fontsize = 22)
plt.ylabel('Temperatura (°C)', fontsize = 22)
plt.title('Resposta a rampa', fontsize = 24)
plt.legend(loc = 'upper left', fontsize = 22)
plt.savefig("ComparacaoCompensadorePI.png",bbox_inches='tight')
plt.show()